/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import javax.swing.JOptionPane;
import models.Empleado;
import services.EmpleadoService;

/**
 *
 * @author mbarz
 */
public class EliminarEmpleados extends javax.swing.JFrame {

    EmpleadoService empleadoService;
    VentanaPrincipal principal;

    /**
     * Creates new form EliminarEmpleados
     */
    public EliminarEmpleados(EmpleadoService empleadoService, VentanaPrincipal principal) {
        initComponents();
        this.empleadoService = empleadoService;
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        regresarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese una cedula");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        regresarBoton.setText("Regresar");
        regresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBoton)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarBoton)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!cedulaText.getText().isEmpty()) {
            if (!empleadoService.existeCedula(cedulaText.getText())) {
                Empleado e = empleadoService.buscarEmpleado(cedulaText.getText());
                int elimina = JOptionPane.showConfirmDialog(this, "Desea eliminar al empleado " + e.getNombre() + " " + e.getApellido() + ", con la cedula N#" + e.getCedula());
                if (elimina == JOptionPane.YES_OPTION) {
                    boolean validacion = empleadoService.eliminarEmpleado(cedulaText.getText());
                    if (validacion) {
                        JOptionPane.showMessageDialog(this, "Se ha eliminado el empleado correctamente");
                        cedulaText.setText("");
                        this.setVisible(false);
                        principal.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se ha podido eliminar al empleado");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe un empleado con esa cedula");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una cedula por favor");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBotonActionPerformed
        cedulaText.setText("");
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_regresarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarBoton;
    // End of variables declaration//GEN-END:variables
}
