/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Empleado;
import models.TipoContrato;
import services.EmpleadoService;
import services.TipoContratoService;

/**
 *
 * @author mbarz
 */
public class ModificarEmpleados extends javax.swing.JFrame {

    EmpleadoService empleadoService;
    TipoContratoService contratoService;
    List<TipoContrato> listaContratos;
    TipoContrato contratoSeleccionado;
    VentanaPrincipal principal;

    /**
     * Creates new form AgregarEmpleado
     */
    public ModificarEmpleados(EmpleadoService empleadoService, TipoContratoService contratoService, VentanaPrincipal principal) {
        initComponents();
        this.empleadoService = empleadoService;
        this.contratoService = contratoService;
        this.principal = principal;
        visibilidad(true);
        listaContratos = contratoService.listarContratos();
        contratoSeleccionado = listaContratos.get(0);
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel) contratoCombo.getModel();
        model.removeAllElements();
        for (TipoContrato contrato : listaContratos) {
            model.addElement(contrato.getDescripcion());
        }
        contratoCombo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cedulaText = new javax.swing.JTextField();
        salarioText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contratoCombo = new javax.swing.JComboBox<>();
        nombreText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoText = new javax.swing.JTextField();
        BuscarEmpleado = new javax.swing.JButton();
        modificarEmpleado = new javax.swing.JButton();
        regresarBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel5.setText("Salario");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel1.setText("Cedula");

        cedulaText.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N

        salarioText.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel6.setText("Tipo Contrato");

        contratoCombo.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        contratoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                contratoComboItemStateChanged(evt);
            }
        });

        nombreText.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel3.setText("Apellido");

        apellidoText.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        jLabel4.setText("Telefono");

        telefonoText.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N

        BuscarEmpleado.setBackground(new java.awt.Color(153, 217, 211));
        BuscarEmpleado.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        BuscarEmpleado.setText("Buscar");
        BuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEmpleadoActionPerformed(evt);
            }
        });

        modificarEmpleado.setBackground(new java.awt.Color(204, 255, 102));
        modificarEmpleado.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        modificarEmpleado.setText("Modificar");
        modificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpleadoActionPerformed(evt);
            }
        });

        regresarBoton.setBackground(new java.awt.Color(255, 102, 102));
        regresarBoton.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        regresarBoton.setText("Regresar");
        regresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBotonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setText("MODIFICAR EMPLEADOS");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/modifi e.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cedulaText, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(nombreText)
                            .addComponent(apellidoText)
                            .addComponent(telefonoText))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(salarioText)
                            .addComponent(contratoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addGap(44, 44, 44)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(modificarEmpleado)
                .addGap(102, 102, 102)
                .addComponent(regresarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarEmpleado)
                    .addComponent(regresarBoton))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpleadoActionPerformed
        if (campos()) {

            String cedula = cedulaText.getText();
            String nombre = nombreText.getText();
            String apellido = apellidoText.getText();
            String telefono = telefonoText.getText();
            String salario = salarioText.getText();
            int idTipoContrato = contratoSeleccionado.getIdTipoContrato();
            Empleado e = new Empleado(cedula, nombre, apellido, telefono, salario, idTipoContrato);
            boolean validacion = empleadoService.modificarEmpleado(e);
            if (validacion) {
                JOptionPane.showMessageDialog(this, "Se ha modificado el empleado correctamente");
                limpiarCampos();
                this.setVisible(false);
                principal.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al modificar el empleado");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Rellene todo los campos por favor");

        }
    }//GEN-LAST:event_modificarEmpleadoActionPerformed

    private void contratoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_contratoComboItemStateChanged
        int index = contratoCombo.getSelectedIndex();
        contratoSeleccionado = listaContratos.get(index);
    }//GEN-LAST:event_contratoComboItemStateChanged

    private void regresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBotonActionPerformed
        limpiarCampos();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_regresarBotonActionPerformed

    private void BuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEmpleadoActionPerformed
        if (!cedulaText.getText().isEmpty()) {
            Empleado e = empleadoService.buscarEmpleado(cedulaText.getText());
            if (e != null) {
                visibilidad(false);
                nombreText.setText(e.getNombre());
                apellidoText.setText(e.getApellido());
                telefonoText.setText(e.getTelefono());
                salarioText.setText(e.getSalario());

                for (int i = 0; i < listaContratos.size(); i++) {
                    if (listaContratos.get(i).getIdTipoContrato() == e.getIdTipoContrato()) {
                        contratoCombo.setSelectedIndex(i);
                        contratoSeleccionado = listaContratos.get(i);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ningun empleado con esa cedula");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una cedula");
        }
    }//GEN-LAST:event_BuscarEmpleadoActionPerformed

    private boolean campos() {
        return !cedulaText.getText().isEmpty()
                && !nombreText.getText().isEmpty()
                && !apellidoText.getText().isEmpty()
                && !telefonoText.getText().isBlank()
                && !salarioText.getText().isEmpty();
    }

    private void limpiarCampos() {
        cedulaText.setText("");
        nombreText.setText("");
        apellidoText.setText("");
        telefonoText.setText("");
        salarioText.setText("");
        contratoCombo.setSelectedIndex(0);

        visibilidad(true);
    }

    private void visibilidad(boolean v) {
        cedulaText.setEnabled(v);
        BuscarEmpleado.setEnabled(v);
        nombreText.setEnabled(!v);
        apellidoText.setEnabled(!v);
        telefonoText.setEnabled(!v);
        salarioText.setEnabled(!v);
        contratoCombo.setEnabled(!v);
        modificarEmpleado.setEnabled(!v);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarEmpleado;
    private javax.swing.JTextField apellidoText;
    private javax.swing.JTextField cedulaText;
    private javax.swing.JComboBox<String> contratoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarEmpleado;
    private javax.swing.JTextField nombreText;
    private javax.swing.JButton regresarBoton;
    private javax.swing.JTextField salarioText;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
